### PR TITLE
Added little message in login for people who do not know SOLID

### PR DESCRIPTION
**Pull request by mocomacode**
This should help to raise awareness about the SOLID project, data decentralization and such htings, instead of just driving customers away.

### CODE REVIEW

**Review by nic9las — CHANGES_REQUESTED** [review]
change the localhostendpoints to the heroku ones plz

**Comment by mocomacode** [comment]
> change the localhostendpoints to the heroku ones plz

Fuck you

**Comment by nic9las** [comment]
> > change the localhostendpoints to the heroku ones plz
> 
> Fuck you

image
i want this disgusting man to be expelled from life

**Comment by mocomacode** [comment]
S

> > > change the localhostendpoints to the heroku ones plz
> > 
> > 
> > Fuck you
> 
> image i want this disgusting man to be expelled from life

image
Says the mf with the pokemon pfp

**Pull request merged**
